### ISSUE TITLE
Cannot see some connection types

### ISSUE THREAD

**Issue by GPirrera** [blackducksoftware/detect-for-tfs#11]
The following issue has been reproduced on multiple Azure DevOps environments,s.

After installing the latest version of Synopsys Detect v2.0.16, I am unable to see the “Black Duck” (Service Endpoint for Black Duck connections) Service Connection type, and I am unable to see the “Polaris” (Service Endpoint for Polaris connections) Service Connection type. It appears that only the “Black Duck Proxy” Service Connection Type was added. [Based on the source code, lines 68-221](https://github.com/blackducksoftware/detect-for-tfs/blob/master/vsts-extension.json), there should be a total of 3 Service Connection Types added.

Screenshots attached.
I also attached the fix in the zip. I tested this on my personal Azure DevOps account, and the endpoints were successfully included with the fix.

![synopysdetect1](https://user-images.githubusercontent.com/17435472/64634708-e5e01300-d3cb-11e9-87d6-6f9ac28f1218.png)
![synopysdetect2](https://user-images.githubusercontent.com/17435472/64634713-e9739a00-d3cb-11e9-9a93-088626b31f9b.png)

[vsts-extension.zip](https://github.com/blackducksoftware/detect-for-tfs/files/3596905/vsts-extension.zip)

**Comment by taikuukaits** [comment]
Would you be willing to do the fix as a PR?

**Comment by taikuukaits** [comment]
That PR should be on the new repo: https://github.com/blackducksoftware/synopsys-coverity-azure-devops

**Comment by taikuukaits** [comment]
I applied your changes from the zip. We will test and verify then release a new plugin version. I wanted to give you credit as a PR but this is fine 👍

**Comment by GPirrera** [comment]
No worries about the credit :). Thanks for the quick turnaround!

**Comment by taikuukaits** [comment]
Released 2.0.17, issue looks to be resolved! Thanks for the changes!
