### ISSUE TITLE
Azure DevOps cannot find the JRE

### ISSUE THREAD

**Issue by JSalazar88** [blackducksoftware/detect-for-tfs#6]
Pool: Hosted VS2017

Got the error:
Scanning target D:\a\1\s failed: There was a problem scanning target 'D:\a\1\s': Could not find the 'jre' directory in C:\Users\VssAdministrator\blackduck\tools.

From the build task:
> 2019-04-01 13:07:03 INFO  [main] --- Starting the Black Duck Signature Scan commands.
> 2019-04-01 13:07:03 INFO  [main] --- Completed the Black Duck Signature Scan commands.
> 2019-04-01 13:07:03 ERROR [main] **--- Scanning target D:\a\1\s failed: There was a problem scanning target 'D:\a\1\s': Could not find the 'jre' directory in C:\Users\VssAdministrator\blackduck\tools.**

More Output Lines:

> ******************************************************************************
> START OF DETECT
> ******************************************************************************
> Detect Powershell Script 1.0.1
> Checking if Java is installed by asking for version.
> Java Standard Output: 
> Java Error Output: openjdk version "1.8.0_202"
> OpenJDK Runtime Environment (Zulu 8.36.0.1-win64)-Microsoft-Azure-restricted (build 1.8.0_202-b05)
> OpenJDK 64-Bit Server VM (Zulu 8.36.0.1-win64)-Microsoft-Azure-restricted (build 25.202-b05, mixed mode)
> 
> Successfully able to start java and get version.
> Initializing detect folder.
> Using system temp folder: C:\Users\VSSADM\~1\AppData\Local\Temp
> Checking for proxy.
> Skipping proxy, no host found.
> Getting detect.
> Finding latest detect version.
> ##[debug]GET https://repo.blackducksoftware.com/artifactory/api/storage/bds-integrations-release/com/blackducksoftware/integration/hub-detect?properties=DETECT_LATEST with 0-byte payload
> ##[debug]received -1-byte response of content type application/vnd.org.jfrog.artifactory.storage.ItemProperties+json
> Resolved detect source https://repo.blackducksoftware.com:443/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-detect/5.3.1/synopsys-detect-5.3.1.jar
> Using detect source https://repo.blackducksoftware.com:443/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-detect/5.3.1/synopsys-detect-5.3.1.jar
> Using detect version 5.3.1
> Detect jar exists 'False'
> You don't have detect. Downloading now.
> Using url https://repo.blackducksoftware.com:443/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-detect/5.3.1/synopsys-detect-5.3.1.jar
> ##[debug]GET https://repo.blackducksoftware.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-detect/5.3.1/synopsys-detect-5.3.1.jar with 0-byte payload
> ##[debug]received 29400286-byte response of content type application/java-archive
> Downloaded detect jar successfully 'True'
> Executing detect.
> Running detect: "-jar" "C:\Users\VSSADM~1\AppData\Local\Temp/hub-detect-5.3.1.jar" "--blackduck.offline.mode" "=" "true"
> ______     _            _
> |  _  \   | |          | |
> | | | |___| |_ ___  ___| |_
> | | | / _ \ __/ _ \/ __| __|
> | |/ /  __/ ||  __/ (__| |_
> |___/ \___|\__\___|\___|\__|
> 
> 2019-04-01 13:06:58 INFO  [main] --- Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6aceb1a5: startup date [Mon Apr 01 13:06:58 UTC 2019]; root of context hierarchy
> 2019-04-01 13:06:58 INFO  [main] --- Preparing detect.
> 2019-04-01 13:06:59 INFO  [main] --- Detect boot begin.
> 2019-04-01 13:07:01 INFO  [main] --- You seem to be running in a WINDOWS operating system.
> 
> Detect Version: 5.3.1

..
..
..

> 2019-04-01 13:07:02 INFO  [main] --- ======================================================================================================
> 2019-04-01 13:07:02 INFO  [main] --- Extraction results:
> 2019-04-01 13:07:02 INFO  [main] --- ======================================================================================================
> 2019-04-01 13:07:02 INFO  [main] --- ======================================================================================================
> 2019-04-01 13:07:02 INFO  [main] --- 
> 2019-04-01 13:07:02 INFO  [main] --- Creating BDIO files from code locations.
> 2019-04-01 13:07:02 INFO  [main] --- Completed Detect Code Location processing.
> 2019-04-01 13:07:02 INFO  [main] --- ----------------------------------
> 2019-04-01 13:07:02 INFO  [main] --- Will include the signature scanner tool.
> 2019-04-01 13:07:02 INFO  [main] --- Will run the signature scanner tool.
> 2019-04-01 13:07:03 INFO  [main] --- No scan targets provided - registering the source path D:\a\1\s to scan
> 2019-04-01 13:07:03 WARN  [main] --- Maximum depth 4 hit while traversing source tree to generate signature scanner exclusion patterns. To search deeper, adjust the value of property Exclusion Patterns Search Depth
> 2019-04-01 13:07:03 INFO  [main] --- Starting the Black Duck Signature Scan commands.
> 2019-04-01 13:07:03 INFO  [main] --- Completed the Black Duck Signature Scan commands.
> 2019-04-01 13:07:03 ERROR [main] **--- Scanning target D:\a\1\s failed: There was a problem scanning target 'D:\a\1\s': Could not find the 'jre' directory in C:\Users\VssAdministrator\blackduck\tools.**
> 2019-04-01 13:07:03 INFO  [main] --- Signature scanner actions finished.

**Comment by taikuukaits** [comment]
If you are offline, you must have the signature scanner downloaded already to use it.
