### ISSUE TITLE
README link to documentation incorrect

### ISSUE THREAD

**Issue by thomasvdb** [blackducksoftware/detect-for-tfs#7]
The link in the README to the Public Confluence is incorrect: https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/622655/Running+Hub+Detect+with+TFS+or+Azure+DevOps

**Comment by taikuukaits** [comment]
Thanks for the heads up. Resolved. 
Now points to: https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/622618/Synopsys+Detect+Extension+for+Azure+DevOps
