### ISSUE TITLE
Cleanup versions during upload

### ISSUE THREAD

**Issue by thomasvdb** [blackducksoftware/detect-for-tfs#8]
Is it possible to configure how many versions should be kept when a new version is uploaded?
We run a weekly scan of the project and only want to keep 5 versions. Older versions can be deleted.

Is this possible?

**Comment by taikuukaits** [comment]
This is not currently possible.

**Comment by thomasvdb** [comment]
Are there any plans to add this feature?

**Comment by akamen** [comment]
@thomasvdb  we currently cannot think of a way to implement this.  Have to close for now.
